studyDjango/Day06(DB_Check2)/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('index/', views.index, name = "index"),
    path('detail/<bpk>', views.detail, name = "detail"),
    path('delete/<bpk>', views.delete, name = "delete")
]

studyDjango/Day06(DB_Check2)/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls"))
]

studyDjango/Day06(DB_Check2)/board/models.py
from django.db import models


# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    likey = models.IntegerField()

    def __str__(self):
        return self.subject

    def summary(self):
        return self.content[:150] + "..."

    def hot(self):
        if self.likey > 20:
            return True
        return False

studyDjango/Day06(DB_Check2)/board/views.py
from django.shortcuts import render, redirect
from .models import Board


# Create your views here.
def index(request):
    b = Board.objects.all()
    context = {
        "bset": b
    }
    return render(request, "board/index.html", context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    context = {
        "b": b
    }
    return render(request, "board/detail.html", context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    b.delete()
    return redirect("board:index")

studyDjango/Day06(DB_Check2)/templates/board/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ b.subject }}</h1>

    <textarea rows = "15" cols = "100" disabled>{{ b.content }}</textarea>

    <br><br><br>

     <!--<a href = "/board/index/"><button>HOME</button></a>-->
         <a href = "{% url 'board:index' %}"><button>HOME</button></a>
         <a href = "{% url 'board:delete' b.id %}"><button>DELETE</button></a>
</body>
</html>

studyDjango/Day06(DB_Check2)/templates/board/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table border = "1">
        <tr>
            <th>No.</th>
            <th>Subject</th>
            <th>Content</th>
            <th>Like</th>
        </tr>

        {% if bset %}
            {% for i in bset %}
                <tr {% if i.hot %} style="background-color: aquamarine" {% endif %}>
                    <td>{{ forloop.counter }}</td>
                    <td><a href = "{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.summary }}</td>
                    <td>{{ i.likey }}</td>
                </tr>
            {% endfor %}
        {% else %}
        <tr>
            <th clospan = "4">No DATA</th>
        </tr>
        {% endif %}
    </table>
</body>
</html>